#!/bin/bash
set -Ceux

ARGS=${@:2}

case $1 in
"init")
    cp ./env.example .env
    ./vendor/bin/sail up
;;
"up")
    ./vendor/bin/sail up
;;
"down")
    ./vendor/bin/sail down
;;
"build")
    ./vendor/bin/sail build $ARGS
;;
"composer")
    ./vendor/bin/sail composer $ARGS
;;
"artisan")
    ./vendor/bin/sail artisan $ARGS
;;
"npm")
    ./vendor/bin/sail npm $ARGS
;;
"yarn")
    ./vendor/bin/sail yarn $ARGS
;;
"db:user")
    ./vendor/bin/sail artisan db:seed --class=UserSeeder
;;
"db:reset")
    ./vendor/bin/sail artisan migrate:reset
    ./vendor/bin/sail artisan migrate
    ./vendor/bin/sail artisan db:seed
;;
"prod:pull")
    git fetch
    git reset --hard origin/main
;;
"prod:update")
    composer update
    yarn prod
;;
"composer:init")
    docker run --rm \
        -u "$(id -u):$(id -g)" \
        -v $(pwd):/var/www/html \
        -w /var/www/html \
        laravelsail/php74-composer:latest \
        composer install --ignore-platform-reqs
;;
*)
    echo Unexpected command.
;;
esac
